### ISSUE TITLE
timeseries in state??

### ISSUE THREAD

**Issue by tarcadius** [IM3S/LDAR_Sim#25] opened 2021-06-04 03:29 UTC
Should timeseries be stored inside of "state" rather than being standalone? Not sure it matters much. Let me know thoughts - that came to mind when making parameter map because it seemed funny to have them separate.

@tbarchyn @KeeganShaw-GIS let me know

**Comment by AkaMrmuffin** [comment] 2021-06-10 17:08
**I found a problem that relates to this issue. I am integrating the agent-level scheduling and there is a wired error:** 
Traceback (most recent call last):
  File "C:\Users\cookg\.conda\envs\LDARSim\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\cookg\.conda\envs\LDARSim\lib\multiprocessing\pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "D:\LDAR_Sim-master\LDAR_sim_scheduling_0608\LDAR_Sim\model_code\ldar_sim_run.py", line 152, in ldar_sim_run
    sim_summary = sim.finalize()
  File "D:\LDAR_Sim-master\LDAR_sim_scheduling_0608\LDAR_Sim\model_code\ldar_sim.py", line 434, in finalize
    time_df = pd.DataFrame(self.timeseries)
  File "C:\Users\cookg\.conda\envs\LDARSim\lib\site-packages\pandas\core\frame.py", line 529, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "C:\Users\cookg\.conda\envs\LDARSim\lib\site-packages\pandas\core\internals\construction.py", line 287, in init_dict
    return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "C:\Users\cookg\.conda\envs\LDARSim\lib\site-packages\pandas\core\internals\construction.py", line 80, in arrays_to_mgr
    index = extract_index(arrays)
  File "C:\Users\cookg\.conda\envs\LDARSim\lib\site-packages\pandas\core\internals\construction.py", line 401, in extract_index
    raise ValueError("arrays must all be same length")
ValueError: arrays must all be same length
"""


The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "D:\LDAR_Sim-master\LDAR_sim_scheduling_0608\LDAR_Sim\model_code\ldar_sim_main.py", line 83, in <module>
    res = p.starmap(ldar_sim_run, simulations)

  File "C:\Users\cookg\.conda\envs\LDARSim\lib\multiprocessing\pool.py", line 276, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()

  File "C:\Users\cookg\.conda\envs\LDARSim\lib\multiprocessing\pool.py", line 657, in get
    raise self._value

ValueError: arrays must all be same length

**I suspect this is due to the scheduling and travel time calculation from euclidian distance limiting the agent's travelling. Therefore, fields in the timeseries 
'active_leaks',
 'new_leaks',
 'n_tags',
 'rolling_cost_estimate',
 'cum_repaired_leaks',
 'daily_emissions_kg',
 'truck_prop_sites_avail'  are not updated at the end of the day since the agent did nothing except travel from one home base to another home base close to the next target facility. In other words, data recorded from state['t'] have different lengths to data stored in timeseries.  For now, this is fixed by automatically check the length of each field. However, to avoid similar issue we should merge timeseries into state. **

**Comment by tarcadius** [comment] 2021-06-10 18:43
Thanks @AkaMrmuffin this is really good to bring up. I've seen this error before and I think it relates to the "roll over" functionality and the fact that if a crew works too long and it becomes the next day, when they're finished working the model goes to the next day again, so they effectively skip a day.

Are you able to take a stab at this one while working on the scheduling stuff?

**Comment by tarcadius** [comment] 2021-06-10 19:27
Thanks @AkaMrmuffin  - yeah we should likely avoid a bandaid solution for this if possible because something fundamentally wrong is going on if the days don't add up.

**Comment by tarcadius** [comment] 2021-08-06 02:35
What's the status on this one?

**Comment by AkaMrmuffin** [comment] 2021-08-09 16:11
The timeseries are still standalone. The bugs/errors of unequal timeseries length caused by route planning or rollover are already fixed.

**Comment by tarcadius** [comment] 2021-08-20 17:40
So should we close this or do you think we should combine timeseries into state? Just leave it and close this?

**Comment by AkaMrmuffin** [comment] 2021-08-22 02:32
I think we can leave it for now since it doesn't really affect any functionality, especially for LDAR Sim V2. If these two need to be combined in the future, we can always do it.

**Closed by AkaMrmuffin** 2021-08-22 02:32 UTC
Labels: bug, enhancement
